[package]
name = "sqlite-parser-proto"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.97"
cc = "1.2.17"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"

[build-dependencies]
cc = "1.0"
