/* automatically generated by rust-bindgen 0.71.1 */

unsafe extern "C" {
    pub fn sqlite3_keyword_check(
        zName: *const ::std::os::raw::c_char,
        nName: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
