[package]
name = "scanner"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "driver"
path = "src/bin/driver/main.rs"

[dependencies]
sqlite-parser-proto = { path = "../..", features = ["parser_generated"] }
anyhow = { workspace = true }
cstree = { workspace = true }
